### ISSUE TITLE
Workflow flowchart

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/poster-isec2018#1]
@dill 
Not sure there is much of a flowchart to make (from the users' perspective) given there are only 3 user-called functions.

convert_project()  --> run_analyses()  --> test_stats()

I must be missing something.  Fill me in.

**Comment by dill** [comment]
It’s not but it does make it clear what you need to do. The poster can serve as additional documentation (maybe even a vignette) so I think this is still useful.

Additionally this is only one use case, perhaps another line from convert project is to go into a bigger MRDS analysis or DSM analysis, plotting results etc ?

**Comment by erex** [comment]
OK--thanks, I'll have a crack at it

**Comment by dill** [comment]
stale issue, closing.
