### ISSUE TITLE
Comments from Len

### ISSUE THREAD

**Issue by lenthomas** [DistanceDevelopment/poster-isec2018#4]
I had a quick look through the poster.  Looks good to me.  A few comments:

- University of St Andrews logo is a bit high - needs to come down the page a wee bit
- Title - could put a line break after "Windows" to make the first line less long
- Introduction. Suggest more background.  For example: 
The Distance software \citep{thomas_distance_2010} has been downloaded >40,000 times in its 20-year history.  It consists of a Windows-based Graphical User Interface (GUI) that gives users ready access to survey design tools (written in Visual Basic) and analysis engines (written in FORTRAN and, more recently, R).  For some users, there my be benifits to performing their analyses directly with the underlying R code, rather than working with the GUI.
- Object produced by... need a comma after "(analysis)"?
- Object produced by... I didn't really understand what is meant by "The nature of the analysis" - could this sentence be reduced in length and tightened up?

Cheers!

**Comment by erex** [comment]
happy to add these, thanks for looking

**Comment by erex** [comment]
believe each of the bullets have been addressed.
