### ISSUE TITLE
Website logo

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/poster-isec2018#5]
Afraid white background is no good; need transparent background.  Can you provide?

**Comment by lenthomas** [comment]
Which logo are you referring to, and who are you asking to provide it? :)

**Comment by erex** [comment]
Upper right corner of poster--Dave has provided logo with white background.

**Comment by lenthomas** [comment]
Aha, yes.  I did look at the pdf a few minutes ago and I didn't see that.  Over to you @dill !  At worst I can probably work out how to turn white into transparent... let me know if you want me to look into it.

**Comment by erex** [comment]
The white background isn't what is needed.

Fall-back position is to go back to original graphic in the upper right corner and simply have text "Visit distancesampling.org for latest information regarding both Distance GUI and R packages" underneath the QR codes.

**Comment by erex** [comment]
I'm nearly beyond caring, but this is what the transparent logo looks like magnified to 100% (actual size when printed on the poster):

![image](https://user-images.githubusercontent.com/330744/41348830-ca09cff8-6f05-11e8-95e9-b543489feae2.png)
there is ghosting around the lettering.  Worth getting excited over?

**Comment by dill** [comment]
I'll fix this this evening and push the result.

**Comment by erex** [comment]
appreciate the help Dave, thanks

**Comment by dill** [comment]
Does 85d91df look acceptable?

**Comment by erex** [comment]
@dill 

The PDF of the poster with the new logo looks fab even at 150% magnification.  Not only is the white shadowing gone, but the letters themselves are much clarified.  Thanks.  I'll give another read-through of the text and all being well, I'll send over to Printing Services tomorrow.

**Comment by dill** [comment]
stale issue, closing.
